# Generated by Django 2.2 on 2019-08-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtesting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptask',
            name='assigned_member',
            field=models.CharField(choices=[('David', 'David'), ('Hamid', 'Hamid'), ('None', 'None'), ('Florian', 'Florian'), ('William', 'William'), ('Rodolphe', 'Rodolphe'), ('Guillaume', 'Guillaume')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='auteur',
            field=models.CharField(choices=[('Hamid', 'Hamid'), ('David', 'David'), ('Rodolphe', 'Rodolphe'), ('Florian', 'Florian'), ('William', 'William'), ('Guillaume', 'Guillaume')], default='David', max_length=200),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='field',
            field=models.CharField(choices=[('IA', 'IA'), ('MANAGEMENT', 'MANAGEMENT'), ('FRONT END WEB', 'FRONT END WEB'), ('HARDWARE', 'HARDWARE'), ('BACK END WEB', 'BACK END WEB'), ('SOFTWARE', 'SOFTWARE')], default='SOFTWARE', max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=models.CharField(choices=[('FINAL PART', 'FINAL PART'), ('INTER SPRINT', 'INTER SPRINT'), ('PRE FOLLOW UP', 'PRE FOLLOW UP')], default='INTER SPRINT', max_length=200),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='auteur',
            field=models.CharField(choices=[('Hamid', 'Hamid'), ('David', 'David'), ('Rodolphe', 'Rodolphe'), ('Florian', 'Florian'), ('William', 'William'), ('Guillaume', 'Guillaume')], default='David', max_length=200),
        ),
    ]
