# Generated by Django 2.2 on 2019-06-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtesting', '0002_auto_20190611_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timelinedays',
            old_name='seq_nbr',
            new_name='measurement_nbr',
        ),
        migrations.AddField(
            model_name='timelinedays',
            name='acceptance_criteria',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='timelinedays',
            name='param',
            field=models.CharField(choices=[('pH', 'pH'), ('pCO2', 'p02'), ('Hct', 'Hct'), ('Na', 'Na'), ('K', 'K'), ('Ca++', 'Ca++'), ('Cl', 'Cl'), ('GLU', 'GLU'), ('LAC', 'LAC'), ('tHb', 'tHb'), ('SO2', 'SO2'), ('Bili', 'Bili'), ('Hb', 'Hb')], default='pH', max_length=200),
        ),
        migrations.AddField(
            model_name='timelinedays',
            name='seq_name',
            field=models.CharField(default='Sequence', max_length=200),
        ),
        migrations.AddField(
            model_name='timelinedays',
            name='target_value',
            field=models.FloatField(default=0),
        ),
    ]
