# Generated by Django 2.2 on 2019-06-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtesting', '0003_auto_20190612_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinedays',
            name='day_nbr',
            field=models.IntegerField(default=0),
        ),
    ]
