# Generated by Django 2.2 on 2019-06-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtesting', '0004_timelinedays_day_nbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelinedays',
            name='lvl_nbr',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='timelinedays',
            name='measurement_nbr',
            field=models.IntegerField(default=0),
        ),
    ]
