# Generated by Django 2.2 on 2019-06-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtesting', '0006_auto_20190612_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='experiment_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='experiment_goal',
            field=models.TextField(),
        ),
    ]
