# Generated by Django 2.2 on 2019-06-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labtesting', '0007_auto_20190613_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicenames',
            name='version',
        ),
    ]
