# Generated by Django 2.2 on 2019-06-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtesting', '0009_auto_20190614_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencedefinition',
            name='break_def',
            field=models.CharField(default='', max_length=50),
        ),
    ]
