# Generated by Django 2.2 on 2019-06-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtesting', '0010_sequencedefinition_break_def'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequences',
            name='sample_matrix',
            field=models.CharField(choices=[('Whole blood', 'Whole blood'), ('Serum', 'Serum'), ('Plasma', 'Plasma')], default='Whole blood', max_length=200),
        ),
        migrations.AddField(
            model_name='sequences',
            name='sample_type',
            field=models.CharField(choices=[('Syringe', 'Syringe'), ('Capillary', 'Capillary')], default='Capillary', max_length=200),
        ),
    ]
