# Generated by Django 2.2 on 2019-06-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtesting', '0011_auto_20190618_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='project_type',
            field=models.CharField(choices=[('Software verification', 'Software verification'), ('Precision', 'Precision'), ('Interference', 'Interference'), ('Method comparison', 'Method comparison'), ('Throughput', 'Throughput'), ('Linearity', 'Linearity')], default='None', max_length=100),
        ),
    ]
