# Generated by Django 2.2 on 2019-06-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtesting', '0012_auto_20190618_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinedays',
            name='sample_matrix',
            field=models.CharField(choices=[('Serum', 'Serum'), ('Whole blood', 'Whole blood'), ('Plasma', 'Plasma')], default='Whole blood', max_length=200),
        ),
        migrations.AddField(
            model_name='timelinedays',
            name='sample_type',
            field=models.CharField(choices=[('Syringe', 'Syringe'), ('Capillary', 'Capillary')], default='Capillary', max_length=200),
        ),
        migrations.AlterField(
            model_name='sequences',
            name='sample_matrix',
            field=models.CharField(choices=[('Serum', 'Serum'), ('Whole blood', 'Whole blood'), ('Plasma', 'Plasma')], default='Whole blood', max_length=200),
        ),
        migrations.AlterField(
            model_name='setup',
            name='project_type',
            field=models.CharField(choices=[('Interference', 'Interference'), ('Method comparison', 'Method comparison'), ('Throughput', 'Throughput'), ('Linearity', 'Linearity'), ('Software verification', 'Software verification'), ('Precision', 'Precision')], default='None', max_length=100),
        ),
    ]
