# Generated by Django 2.2 on 2019-06-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtesting', '0013_auto_20190618_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinedays',
            name='break_def',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='timelinedays',
            name='pause_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sequences',
            name='sample_matrix',
            field=models.CharField(choices=[('Plasma', 'Plasma'), ('Serum', 'Serum'), ('Whole blood', 'Whole blood')], default='Whole blood', max_length=200),
        ),
        migrations.AlterField(
            model_name='sequences',
            name='sample_type',
            field=models.CharField(choices=[('Capillary', 'Capillary'), ('Syringe', 'Syringe')], default='Capillary', max_length=200),
        ),
        migrations.AlterField(
            model_name='setup',
            name='project_type',
            field=models.CharField(choices=[('Linearity', 'Linearity'), ('Software verification', 'Software verification'), ('Interference', 'Interference'), ('Throughput', 'Throughput'), ('Method comparison', 'Method comparison'), ('Precision', 'Precision')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='timelinedays',
            name='sample_matrix',
            field=models.CharField(choices=[('Plasma', 'Plasma'), ('Serum', 'Serum'), ('Whole blood', 'Whole blood')], default='Whole blood', max_length=200),
        ),
        migrations.AlterField(
            model_name='timelinedays',
            name='sample_type',
            field=models.CharField(choices=[('Capillary', 'Capillary'), ('Syringe', 'Syringe')], default='Capillary', max_length=200),
        ),
    ]
