# Generated by Django 2.2 on 2019-08-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtesting', '0014_auto_20190618_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptif', models.CharField(max_length=2000)),
                ('auteur', models.CharField(choices=[('Rodolphe', 'Rodolphe'), ('William', 'William'), ('Florian', 'Florian'), ('Hamid', 'Hamid'), ('David', 'David'), ('Guillaume', 'Guillaume')], default='David', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('FRONT END WEB', 'FRONT END WEB'), ('MANAGEMENT', 'MANAGEMENT'), ('HARDWARE', 'HARDWARE'), ('BACK END WEB', 'BACK END WEB'), ('IA', 'IA'), ('SOFTWARE', 'SOFTWARE')], default='SOFTWARE', max_length=200)),
                ('descriptif', models.CharField(max_length=2000)),
                ('auteur', models.CharField(choices=[('Rodolphe', 'Rodolphe'), ('William', 'William'), ('Florian', 'Florian'), ('Hamid', 'Hamid'), ('David', 'David'), ('Guillaume', 'Guillaume')], default='David', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_alert', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('descriptif', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('FINAL PART', 'FINAL PART'), ('INTER SPRINT', 'INTER SPRINT'), ('PRE FOLLOW UP', 'PRE FOLLOW UP')], default='INTER SPRINT', max_length=200)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('is_pld_update', models.BooleanField(default=False)),
                ('is_meeting_ready', models.BooleanField(default=False)),
                ('meetings', models.ManyToManyField(to='labtesting.Meeting')),
                ('rapport_mensuel', models.ManyToManyField(to='labtesting.Article')),
            ],
        ),
        migrations.AlterField(
            model_name='sequences',
            name='sample_matrix',
            field=models.CharField(choices=[('Serum', 'Serum'), ('Plasma', 'Plasma'), ('Whole blood', 'Whole blood')], default='Whole blood', max_length=200),
        ),
        migrations.AlterField(
            model_name='sequences',
            name='sample_type',
            field=models.CharField(choices=[('Syringe', 'Syringe'), ('Capillary', 'Capillary')], default='Capillary', max_length=200),
        ),
        migrations.AlterField(
            model_name='setup',
            name='project_type',
            field=models.CharField(choices=[('Method comparison', 'Method comparison'), ('Software verification', 'Software verification'), ('Linearity', 'Linearity'), ('Interference', 'Interference'), ('Precision', 'Precision'), ('Throughput', 'Throughput')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='timelinedays',
            name='sample_matrix',
            field=models.CharField(choices=[('Serum', 'Serum'), ('Plasma', 'Plasma'), ('Whole blood', 'Whole blood')], default='Whole blood', max_length=200),
        ),
        migrations.AlterField(
            model_name='timelinedays',
            name='sample_type',
            field=models.CharField(choices=[('Syringe', 'Syringe'), ('Capillary', 'Capillary')], default='Capillary', max_length=200),
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_name', models.CharField(max_length=200, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('descriptif', models.CharField(max_length=2000)),
                ('sprint_part', models.ManyToManyField(to='labtesting.Part')),
            ],
        ),
    ]
