# Generated by Django 2.2 on 2019-08-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtesting', '0015_auto_20190804_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.CharField(choices=[('Hamid', 'Hamid'), ('David', 'David'), ('Florian', 'Florian'), ('Rodolphe', 'Rodolphe'), ('Guillaume', 'Guillaume'), ('William', 'William')], default='David', max_length=200),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='auteur',
            field=models.CharField(choices=[('Hamid', 'Hamid'), ('David', 'David'), ('Florian', 'Florian'), ('Rodolphe', 'Rodolphe'), ('Guillaume', 'Guillaume'), ('William', 'William')], default='David', max_length=200),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='field',
            field=models.CharField(choices=[('IA', 'IA'), ('SOFTWARE', 'SOFTWARE'), ('FRONT END WEB', 'FRONT END WEB'), ('MANAGEMENT', 'MANAGEMENT'), ('HARDWARE', 'HARDWARE'), ('BACK END WEB', 'BACK END WEB')], default='SOFTWARE', max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=models.CharField(choices=[('INTER SPRINT', 'INTER SPRINT'), ('PRE FOLLOW UP', 'PRE FOLLOW UP'), ('FINAL PART', 'FINAL PART')], default='INTER SPRINT', max_length=200),
        ),
        migrations.AlterField(
            model_name='sequences',
            name='sample_matrix',
            field=models.CharField(choices=[('Plasma', 'Plasma'), ('Whole blood', 'Whole blood'), ('Serum', 'Serum')], default='Whole blood', max_length=200),
        ),
        migrations.AlterField(
            model_name='setup',
            name='project_type',
            field=models.CharField(choices=[('Throughput', 'Throughput'), ('Method comparison', 'Method comparison'), ('Linearity', 'Linearity'), ('Software verification', 'Software verification'), ('Interference', 'Interference'), ('Precision', 'Precision')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='timelinedays',
            name='sample_matrix',
            field=models.CharField(choices=[('Plasma', 'Plasma'), ('Whole blood', 'Whole blood'), ('Serum', 'Serum')], default='Whole blood', max_length=200),
        ),
    ]
