# Generated by Django 2.2 on 2019-08-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtesting', '0016_auto_20190804_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(choices=[('William', 'William'), ('Florian', 'Florian'), ('Hamid', 'Hamid'), ('David', 'David'), ('Guillaume', 'Guillaume'), ('Rodolphe', 'Rodolphe')], default='David', max_length=200)),
                ('nbr_of_points_todo', models.IntegerField(default=0)),
                ('nbr_of_points_done', models.IntegerField(default=0)),
                ('descriptif_done', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.CharField(choices=[('William', 'William'), ('Florian', 'Florian'), ('Hamid', 'Hamid'), ('David', 'David'), ('Guillaume', 'Guillaume'), ('Rodolphe', 'Rodolphe')], default='David', max_length=200),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='auteur',
            field=models.CharField(choices=[('William', 'William'), ('Florian', 'Florian'), ('Hamid', 'Hamid'), ('David', 'David'), ('Guillaume', 'Guillaume'), ('Rodolphe', 'Rodolphe')], default='David', max_length=200),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='field',
            field=models.CharField(choices=[('BACK END WEB', 'BACK END WEB'), ('SOFTWARE', 'SOFTWARE'), ('MANAGEMENT', 'MANAGEMENT'), ('IA', 'IA'), ('HARDWARE', 'HARDWARE'), ('FRONT END WEB', 'FRONT END WEB')], default='SOFTWARE', max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=models.CharField(choices=[('FINAL PART', 'FINAL PART'), ('PRE FOLLOW UP', 'PRE FOLLOW UP'), ('INTER SPRINT', 'INTER SPRINT')], default='INTER SPRINT', max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='rapport_mensuel',
            field=models.ManyToManyField(to='labtesting.Rapport'),
        ),
        migrations.AlterField(
            model_name='sequences',
            name='sample_matrix',
            field=models.CharField(choices=[('Whole blood', 'Whole blood'), ('Serum', 'Serum'), ('Plasma', 'Plasma')], default='Whole blood', max_length=200),
        ),
        migrations.AlterField(
            model_name='setup',
            name='project_type',
            field=models.CharField(choices=[('Linearity', 'Linearity'), ('Throughput', 'Throughput'), ('Interference', 'Interference'), ('Method comparison', 'Method comparison'), ('Software verification', 'Software verification'), ('Precision', 'Precision')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='timelinedays',
            name='sample_matrix',
            field=models.CharField(choices=[('Whole blood', 'Whole blood'), ('Serum', 'Serum'), ('Plasma', 'Plasma')], default='Whole blood', max_length=200),
        ),
    ]
