# Generated by Django 2.2 on 2019-08-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtesting', '0017_auto_20190804_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.CharField(choices=[('Hamid', 'Hamid'), ('Guillaume', 'Guillaume'), ('David', 'David'), ('Florian', 'Florian'), ('Rodolphe', 'Rodolphe'), ('William', 'William')], default='David', max_length=200),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='auteur',
            field=models.CharField(choices=[('Hamid', 'Hamid'), ('Guillaume', 'Guillaume'), ('David', 'David'), ('Florian', 'Florian'), ('Rodolphe', 'Rodolphe'), ('William', 'William')], default='David', max_length=200),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='field',
            field=models.CharField(choices=[('IA', 'IA'), ('HARDWARE', 'HARDWARE'), ('BACK END WEB', 'BACK END WEB'), ('MANAGEMENT', 'MANAGEMENT'), ('SOFTWARE', 'SOFTWARE'), ('FRONT END WEB', 'FRONT END WEB')], default='SOFTWARE', max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=models.CharField(choices=[('INTER SPRINT', 'INTER SPRINT'), ('FINAL PART', 'FINAL PART'), ('PRE FOLLOW UP', 'PRE FOLLOW UP')], default='INTER SPRINT', max_length=200),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='auteur',
            field=models.CharField(choices=[('Hamid', 'Hamid'), ('Guillaume', 'Guillaume'), ('David', 'David'), ('Florian', 'Florian'), ('Rodolphe', 'Rodolphe'), ('William', 'William')], default='David', max_length=200),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='descriptif_done',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sequences',
            name='sample_type',
            field=models.CharField(choices=[('Capillary', 'Capillary'), ('Syringe', 'Syringe')], default='Capillary', max_length=200),
        ),
        migrations.AlterField(
            model_name='setup',
            name='project_type',
            field=models.CharField(choices=[('Method comparison', 'Method comparison'), ('Throughput', 'Throughput'), ('Precision', 'Precision'), ('Software verification', 'Software verification'), ('Linearity', 'Linearity'), ('Interference', 'Interference')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='timelinedays',
            name='sample_type',
            field=models.CharField(choices=[('Capillary', 'Capillary'), ('Syringe', 'Syringe')], default='Capillary', max_length=200),
        ),
    ]
