# Generated by Django 2.2.4 on 2019-08-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtesting', '0018_auto_20190805_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('todo', models.ManyToManyField(to='labtesting.Task')),
            ],
        ),
        migrations.CreateModel(
            name='WikiArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.CharField(max_length=500)),
                ('descriptif', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='auteur',
            field=models.CharField(choices=[('Hamid', 'Hamid'), ('Florian', 'Florian'), ('David', 'David'), ('Guillaume', 'Guillaume'), ('William', 'William'), ('Rodolphe', 'Rodolphe')], default='David', max_length=200),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='field',
            field=models.CharField(choices=[('FRONT END WEB', 'FRONT END WEB'), ('SOFTWARE', 'SOFTWARE'), ('MANAGEMENT', 'MANAGEMENT'), ('IA', 'IA'), ('HARDWARE', 'HARDWARE'), ('BACK END WEB', 'BACK END WEB')], default='SOFTWARE', max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=models.CharField(choices=[('PRE FOLLOW UP', 'PRE FOLLOW UP'), ('INTER SPRINT', 'INTER SPRINT'), ('FINAL PART', 'FINAL PART')], default='INTER SPRINT', max_length=200),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='auteur',
            field=models.CharField(choices=[('Hamid', 'Hamid'), ('Florian', 'Florian'), ('David', 'David'), ('Guillaume', 'Guillaume'), ('William', 'William'), ('Rodolphe', 'Rodolphe')], default='David', max_length=200),
        ),
        migrations.AlterField(
            model_name='sequences',
            name='sample_matrix',
            field=models.CharField(choices=[('Whole blood', 'Whole blood'), ('Plasma', 'Plasma'), ('Serum', 'Serum')], default='Whole blood', max_length=200),
        ),
        migrations.AlterField(
            model_name='setup',
            name='project_type',
            field=models.CharField(choices=[('Precision', 'Precision'), ('Method comparison', 'Method comparison'), ('Software verification', 'Software verification'), ('Linearity', 'Linearity'), ('Throughput', 'Throughput'), ('Interference', 'Interference')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='timelinedays',
            name='sample_matrix',
            field=models.CharField(choices=[('Whole blood', 'Whole blood'), ('Plasma', 'Plasma'), ('Serum', 'Serum')], default='Whole blood', max_length=200),
        ),
    ]
