# Generated by Django 2.2 on 2019-08-19 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labtesting', '0020_auto_20190819_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution'),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='auteur',
            field=models.CharField(choices=[('Rodolphe', 'Rodolphe'), ('Florian', 'Florian'), ('David', 'David'), ('William', 'William'), ('Guillaume', 'Guillaume'), ('Hamid', 'Hamid')], default='David', max_length=200),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='field',
            field=models.CharField(choices=[('BACK END WEB', 'BACK END WEB'), ('FRONT END WEB', 'FRONT END WEB'), ('HARDWARE', 'HARDWARE'), ('IA', 'IA'), ('MANAGEMENT', 'MANAGEMENT'), ('SOFTWARE', 'SOFTWARE')], default='SOFTWARE', max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=models.CharField(choices=[('FINAL PART', 'FINAL PART'), ('PRE FOLLOW UP', 'PRE FOLLOW UP'), ('INTER SPRINT', 'INTER SPRINT')], default='INTER SPRINT', max_length=200),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='auteur',
            field=models.CharField(choices=[('Rodolphe', 'Rodolphe'), ('Florian', 'Florian'), ('David', 'David'), ('William', 'William'), ('Guillaume', 'Guillaume'), ('Hamid', 'Hamid')], default='David', max_length=200),
        ),
        migrations.AlterField(
            model_name='sequences',
            name='sample_matrix',
            field=models.CharField(choices=[('Plasma', 'Plasma'), ('Whole blood', 'Whole blood'), ('Serum', 'Serum')], default='Whole blood', max_length=200),
        ),
        migrations.AlterField(
            model_name='setup',
            name='project_type',
            field=models.CharField(choices=[('Precision', 'Precision'), ('Interference', 'Interference'), ('Software verification', 'Software verification'), ('Method comparison', 'Method comparison'), ('Throughput', 'Throughput'), ('Linearity', 'Linearity')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='timelinedays',
            name='sample_matrix',
            field=models.CharField(choices=[('Plasma', 'Plasma'), ('Whole blood', 'Whole blood'), ('Serum', 'Serum')], default='Whole blood', max_length=200),
        ),
    ]
