# Generated by Django 2.2 on 2019-08-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtesting', '0021_auto_20190819_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='instruments',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='lvl_def',
        ),
        migrations.DeleteModel(
            name='ParametersNames',
        ),
        migrations.RemoveField(
            model_name='project',
            name='checks',
        ),
        migrations.RemoveField(
            model_name='project',
            name='content',
        ),
        migrations.RemoveField(
            model_name='project',
            name='information',
        ),
        migrations.RemoveField(
            model_name='project',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='project',
            name='setup',
        ),
        migrations.RemoveField(
            model_name='project',
            name='timeline',
        ),
        migrations.RemoveField(
            model_name='sequences',
            name='seq',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='devices_names',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='levels',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='seq_def',
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='auteur',
            field=models.CharField(choices=[('William', 'William'), ('Florian', 'Florian'), ('Hamid', 'Hamid'), ('Guillaume', 'Guillaume'), ('David', 'David'), ('Rodolphe', 'Rodolphe')], default='David', max_length=200),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='field',
            field=models.CharField(choices=[('IA', 'IA'), ('MANAGEMENT', 'MANAGEMENT'), ('BACK END WEB', 'BACK END WEB'), ('HARDWARE', 'HARDWARE'), ('FRONT END WEB', 'FRONT END WEB'), ('SOFTWARE', 'SOFTWARE')], default='SOFTWARE', max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=models.CharField(choices=[('FINAL PART', 'FINAL PART'), ('INTER SPRINT', 'INTER SPRINT'), ('PRE FOLLOW UP', 'PRE FOLLOW UP')], default='INTER SPRINT', max_length=200),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='auteur',
            field=models.CharField(choices=[('William', 'William'), ('Florian', 'Florian'), ('Hamid', 'Hamid'), ('Guillaume', 'Guillaume'), ('David', 'David'), ('Rodolphe', 'Rodolphe')], default='David', max_length=200),
        ),
        migrations.DeleteModel(
            name='Checks',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='DeviceNames',
        ),
        migrations.DeleteModel(
            name='Information',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='InstrumentDefinition',
        ),
        migrations.DeleteModel(
            name='LevelDefinition',
        ),
        migrations.DeleteModel(
            name='Levels',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='SequenceDefinition',
        ),
        migrations.DeleteModel(
            name='Sequences',
        ),
        migrations.DeleteModel(
            name='Setup',
        ),
        migrations.DeleteModel(
            name='TimelineDays',
        ),
    ]
