# Generated by Django 2.2 on 2019-08-28 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_member', models.CharField(choices=[('Guillaume', 'Guillaume'), ('David', 'David'), ('Florian', 'Florian'), ('None', 'None'), ('William', 'William'), ('Rodolphe', 'Rodolphe'), ('Hamid', 'Hamid')], default='None', max_length=100)),
                ('task_name', models.CharField(max_length=200)),
                ('task_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(choices=[('Guillaume', 'Guillaume'), ('David', 'David'), ('Florian', 'Florian'), ('William', 'William'), ('Rodolphe', 'Rodolphe'), ('Hamid', 'Hamid')], default='David', max_length=200)),
                ('title', models.CharField(default='Title', max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('field', models.CharField(choices=[('BACK END WEB', 'BACK END WEB'), ('HARDWARE', 'HARDWARE'), ('MANAGEMENT', 'MANAGEMENT'), ('FRONT END WEB', 'FRONT END WEB'), ('IA', 'IA'), ('SOFTWARE', 'SOFTWARE')], default='SOFTWARE', max_length=200)),
                ('descriptif', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_alert', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('descriptif', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('PRE FOLLOW UP', 'PRE FOLLOW UP'), ('FINAL PART', 'FINAL PART'), ('INTER SPRINT', 'INTER SPRINT')], default='INTER SPRINT', max_length=200)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('is_pld_update', models.BooleanField(default=False)),
                ('is_meeting_ready', models.BooleanField(default=False)),
                ('meetings', models.ManyToManyField(to='labtesting.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(choices=[('Guillaume', 'Guillaume'), ('David', 'David'), ('Florian', 'Florian'), ('William', 'William'), ('Rodolphe', 'Rodolphe'), ('Hamid', 'Hamid')], default='David', max_length=200)),
                ('nbr_of_points_todo', models.IntegerField(default=0)),
                ('nbr_of_points_done', models.IntegerField(default=0)),
                ('descriptif_done', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WikiArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('links', models.CharField(max_length=500)),
                ('descriptif', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('todo', models.ManyToManyField(to='labtesting.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_name', models.CharField(max_length=200, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('descriptif', models.CharField(max_length=2000)),
                ('sprint_part', models.ManyToManyField(to='labtesting.Part')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='rapport_mensuel',
            field=models.ManyToManyField(to='labtesting.Rapport'),
        ),
    ]
