# Generated by Django 2.2 on 2019-08-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtesting', '0002_auto_20190828_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptask',
            name='assigned_member',
            field=models.CharField(choices=[('None', 'None'), ('Rodolphe', 'Rodolphe'), ('David', 'David'), ('Florian', 'Florian'), ('William', 'William'), ('Guillaume', 'Guillaume'), ('Hamid', 'Hamid')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='auteur',
            field=models.CharField(choices=[('Rodolphe', 'Rodolphe'), ('David', 'David'), ('Florian', 'Florian'), ('Hamid', 'Hamid'), ('Guillaume', 'Guillaume'), ('William', 'William')], default='David', max_length=200),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='field',
            field=models.CharField(choices=[('HARDWARE', 'HARDWARE'), ('IA', 'IA'), ('BACK END WEB', 'BACK END WEB'), ('MANAGEMENT', 'MANAGEMENT'), ('SOFTWARE', 'SOFTWARE'), ('FRONT END WEB', 'FRONT END WEB')], default='SOFTWARE', max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=models.CharField(choices=[('PRE FOLLOW UP', 'PRE FOLLOW UP'), ('FINAL PART', 'FINAL PART'), ('INTER SPRINT', 'INTER SPRINT')], default='INTER SPRINT', max_length=200),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='auteur',
            field=models.CharField(choices=[('Rodolphe', 'Rodolphe'), ('David', 'David'), ('Florian', 'Florian'), ('Hamid', 'Hamid'), ('Guillaume', 'Guillaume'), ('William', 'William')], default='David', max_length=200),
        ),
    ]
